[package]

name = "intecture-cli"
version = "0.0.2"
authors = [ "Peter Hayes <peter.hayes@betweenlines.co.uk>" ]
license = "MPL-2.0"
description = "CLI component for Intecture infrastructure. Intecture is the developer friendly, multi-lingual configuration management tool."
keywords = ["intecture", "incli", "cli"]
homepage = "https://intecture.io"
repository = "https://github.com/betweenlines/intecture-cli"

[dependencies]

docopt = "0.6.*"
rustc-serialize = "0.3.*"

[[bin]]

name = "incli"
